### ISSUE TITLE
El informe es sobre las decisiones tomadas y su justificación

### ISSUE THREAD

**Issue by JJ** [VictorMorenoJimenez/tfg2020#103]
No es un manual de usuario, no es una descripción de un producto. Es una justificación, hito a hito, de todas las decisiones tomadas y porqué. Habrá cosas que estarán en los requisitos funcionales, y cosas que habrá que decidir (como usar Ansible, por ejemplo).
Todos los retos superados (como parchear errores externos, por ejemplo) deben quedar muy claros en la memoria.

**Comment by VictorMorenoJimenez** [comment]
Entendido. Cierro
