### ISSUE TITLE
Referirse a milestones e issues en la planificación

### ISSUE THREAD

**Issue by JJ** [VictorMorenoJimenez/tfg2020#148]
El trabajo en el repo no puede ser independiente de lo que se ha puesto en la memoria.

**Comment by VictorMorenoJimenez** [comment]
@JJ No entiendo muy bien a qué te refieres, en la planificación he usado los Milestones repartidos en semanas en el diagrama de Gantt

**Comment by JJ** [comment]
@VictorMorenoJimenez "Referirse a" == enlazar

**Comment by VictorMorenoJimenez** [comment]
@JJ Sigo sin entender qué quieres decir

**Comment by JJ** [comment]
Usa enlaces, aquí y en el otro issue donde menciono los milestones.
