### ISSUE TITLE
El capítulo dos es un cajón de sastre

### ISSUE THREAD

**Issue by JJ** [VictorMorenoJimenez/tfg2020#150]
Mezclas análisis del sistema, con metodología, con estado del arte. Estas tres cosas deben estar separadas para poder tratarse con justicia. El análisis por un lado (con requisitos de todo tipo). A continuación el estado del arte *de lo que tú aportes al proyecto* (pfSense estás obligado, pero Ansible no, así que tendrás que centrarte en esto). 
La metodología debe venir a continuación, en otro capítulo. Un requisito funcional se puede implementar de muchas formas diferentes. Tú has usado hitos e issues (y debes decir qué metodología has usado, si Scrum, o lo que sea), así que menciónalo. Posiblemente este capítulo debería fusionarse con "planificación", aunque no tengo muy claro el presupuesto qué opina en esa parte...

**Comment by VictorMorenoJimenez** [comment]
Entiendo, el presupuesto entonces, donde lo puedo encajar?

**Comment by JJ** [comment]
Sinceramente, no sabría decirte. Donde veas que encaja mejor.
