### ISSUE TITLE
Primero requisitos, luego elección

### ISSUE THREAD

**Issue by JJ** [VictorMorenoJimenez/tfg2020#151]
Esto no está bien

"El servicio de virtualización elegido ha sido Proxmox VE [13], basado en
KVM (Kernel-based Virtual Machine) y de código abierto."

En el capítulo de estado del arte (que no has puesto) debe listar diferentes soluciones que correspondan a tus requisitos funcionales. *Al final* de este capítulo es donde debes decir lo que has elegido. Las elecciones en tu TFG son lo más importante, y si dices del tirón "he elegido esto" no demuestran ningún tipo de trabajo ni investigación en el tema.

**Comment by VictorMorenoJimenez** [comment]
He añadido en la sección de requisitos las restricciones de la empresa y en la sección de estado del arte una análisis para elegir la herramienta de automatización.
