### ISSUE TITLE
Relacionar casos de uso con milestones, issues y requisitos funcionales

### ISSUE THREAD

**Issue by JJ** [VictorMorenoJimenez/tfg2020#152]
Los casos de uso no pueden estar en el aire, tienen que relacionarse con el trabajo llevado a cabo (usando enlaces al repo o los nombres de milestones e issues)

**Comment by VictorMorenoJimenez** [comment]
https://github.com/VictorMorenoJimenez/tfg2020/commit/4dd8cf3379330af3d8a8abc5b13b1287be8c8810
