### ISSUE TITLE
Check inline vars like /etc/foo/"{{ user }}"

### ISSUE THREAD

**Issue by VictorMorenoJimenez** [VictorMorenoJimenez/tfg2020#28]
This is not working properly on some scenarios. Replace from:

name: /etc/foo/"{{ user }}"
to
name: "/etc/foo/{{ user }}"

**Comment by JJ** [comment]
If it's not working, it's a bug. And to consider it fixed, there should be a test for those specific scenarios.

**Comment by VictorMorenoJimenez** [comment]
Changed all ocurrencies on playbooks.
