### ISSUE TITLE
Use real deployment tools instead of scripts

### ISSUE THREAD

**Issue by JJ** [VictorMorenoJimenez/tfg2020#93]
What I see in the scripts are several phases, every one of which depends on the previous one and might fail if it's been already done. You should use either Makefiles or use Ansible itself to set it as a series of targets, checking that the previous one has been reached. With any of them you guarantee it's system-independent, and it's a more principled approach to managing and starting a project.

**Comment by VictorMorenoJimenez** [comment]
Issue #107

**Comment by JJ** [comment]
You should always close with a commit. If you've opened another issue to clarify, close both when the other is solved.
